name: "Configure yc"
description: "Installs and configures yc CLI"
inputs:
  name:
    description: "folder name"
    required: true
  owner:
    description: "name_lastname"
    required: true
  expires_at:
    description: "epoch time when resources can be destroyed"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create or update ${{ inputs.name }}
      shell: bash
      run: |
        set -ex
        yc resource-manager folder create ${{ inputs.name }} || /bin/true
        yc resource-manager folder update --name ${{ inputs.name }} --labels "owner=${{ inputs.owner }},expires_at=${{ inputs.expires_at }}"
