name: Expire states
on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch: {}

jobs:

  expire:
    runs-on: ubuntu-latest
    env:
      STATES_DIR: states
    steps:
      - name: clean workspace
        uses: jstone28/runner-workspace-cleaner@v1.0.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - id: get-states
        shell: bash
        run: |
          apt update && apt install -y jq
          echo "states_json=$(find $STATES_DIR -type f -name .expires_at | jq -R . | jq -s .)"

      - id: expire
        shell: bash
        name: Check expiration for ${{ matrix.state_dir }}
        matrix:
          state_dir: ${{ fromJson(needs.get-states.outputs.states_json) }}
        run: |
          cd ${{ matrix.state_dir }}
          now=$(date '+%s')
          expires_at=$(<$file)
        
          difference=$(( $expires_at - $now ))
          
          if [ $difference -le 0 ]; then
            echo "${{ matrix.state_dir }} expired"
          fi

          

