name: Expire states
on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch: {}
  push:
    branches:
      - '*'

jobs:
  get-expired:
    runs-on: ubuntu-latest
    outputs:
      namesJson: ${{ steps.expired.outputs.namesJson }}
    steps:
      - name: clean workspace
        uses: jstone28/runner-workspace-cleaner@v1.0.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/configure-yc-cli
        with:
          token: ${{ secrets.YC_TOKEN }}
          cloud_id: ${{ secrets.YC_CLOUD }}

      - name: Install yq
        shell: bash
        run: |
          sudo apt update && sudo apt install -y wget
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

      - id: expired
        shell: bash
        run: |
          echo "namesJson=$(yc resource-manager folder list --format json | NOW=$(date '+%s') jq  '.[] | select(.labels.expires_at) | select( .labels.expires_at|tonumber <= (env.NOW|tonumber) ) | .name' | jq -s .)" >> $GITHUB_OUTPUT

  expire:
    runs-on: ubuntu-latest
    needs:
      - get-expired
    strategy:
      fail-fast: true
      matrix:
        folder: ${{ fromJson(needs.get-expired.outputs.namesJson ) }}
    steps:
      - name: expiring ${{ matrix.folder }}
        run: |
          echo expired


      


      
          
