name: Process PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  set-expiration:
    env:
      DEFAULT_TTL: "1 day"
    runs-on: ubuntu-latest
    steps:
      - name: clean workspace
        uses: jstone28/runner-workspace-cleaner@v1.0.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - id: changed-state
        uses: ./.github/actions/changes-state

      - id: changed-state
        uses: ./.github/actions/operation
        with:
          state_dir: steps.changed-state.outputs.dir

      - id: expire-at
        shell: bash
        run: |
          cd ${{ steps.}}
