name: Apply tf changes
on:
  push: {}

jobs:
  yc-config:
    runs-on: ubuntu-latest
    steps:
      - name: Install yc
        run: |
          apt update && apt install -y curl
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Configure yc
        run: |
          cat ${{ secrets.YC_CONFIG }} > /root/.config/yandex-cloud/config.yaml

      - run: |
          yc config profile list