name: Apply tf changes
on:
  workflow_dispatch: {}
  push:
    branches:
    - '*'
    paths:
    - 'states/**'

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      folder_name: ${{ steps.get-changes.outputs.folder_name }}
      owner: ${{ steps.get-changes.outputs.owner }}
      expires_at: ${{ steps.get-changes.outputs.expires_at }}
    steps:
      - name: clean workspace
        uses: jstone28/runner-workspace-cleaner@v1.0.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/get-changes
        id: get-changes

  terraform:
    runs-on: ubuntu-latest
    needs:
      - get-changes
    steps:
      - name: clean workspace
        uses: jstone28/runner-workspace-cleaner@v1.0.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/configure-yc-cli
        with:
          token: ${{ secrets.YC_TOKEN }}
          cloud_id: ${{ secrets.YC_CLOUD }}

      - name: Configure folder
        uses: ./.github/actions/create-yc-folder
        with:
          name: ${{ needs.get-changes.outputs.folder_name }}
          owner: ${{ needs.get-changes.outputs.owner }}
          expires_at: ${{ needs.get-changes.outputs.expires_at }}

      - name: Run terraform
        env:
          STATE_DIR: states/${{ needs.get-changes.outputs.folder_name }}
          FOLDER_NAME: ${{ needs.get-changes.outputs.folder_name }}
        shell: bash
        run: |
          set -e
          docker run --rm \
            --env YC_TOKEN \
            --env YC_CLOUD_ID \
            --volume $(pwd):/workdir \
            --workdir /workdir/${{ env.STATE_DIR }} \
            --entrypoint="" \
            hashicorp/terraform:1.3.6  \
              sh -c 'env; terraform init'
        


          
