name: Apply tf changes
on:
  workflow_dispatch: {}
  push:
    branches:
    - '*'
    paths:
    - 'states/**'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get state directories
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: states
          dir_names: true
          dir_names_max_depth: 2

      - run: |
          changed_dirs=(${{ steps.changed-files.outputs.all_changed_files }})
          
          # debug
          for dir in ${changed_dirs[@]}; do
            echo "$(basename $dir) changed"
          done
          
          if [ ${#changed_dirs[@]} -gt 1 ]; then
            echo "⛔️Only one state change per branch is supported, split your code changes."
            exit 1
          fi

  yc-config:
    runs-on: ubuntu-latest
    needs:
      - check-changes
    steps:
      - name: Install yc
        run: |
          apt update && apt install -y curl
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Configure yc
        shell: bash
        run: |
          PATH="~/yandex-cloud/bin:$PATH"
          yc config profile create default
          yc config set token '{{ secrets.YC_TOKEN }}'
          yc config set cloud-id '{{ secrets.YC_CLOUD }}'
      
      - name: Get YC_FOLDER
        shell: bash
        run: |
          PATH="~/yandex-cloud/bin:$PATH"
          yc resource-manager folder create --name {{ }}