name: Apply tf changes
on:
  workflow_dispatch: {}
  push:
    branches:
    - '*'
    paths:
    - 'states/**'

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      yc_folder_name: ${{ steps.get-changes.outputs.yc_folder_name }}
      yc_owner: ${{ steps.get-changes.outputs.yc_owner }}
      yc_expires_at: ${{ steps.get-changes.outputs.yc_expires_at }}
    steps:
      - name: clean workspace
        uses: jstone28/runner-workspace-cleaner@v1.0.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/get-changes
        id: get-changes

  yc-config:
    runs-on: ubuntu-latest
    needs:
      - get-changes
    env:
    steps:
      - name: clean workspace
        uses: jstone28/runner-workspace-cleaner@v1.0.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/configure-yc-cli
        with:
          token: ${{ secrets.YC_TOKEN }}
          cloud_id: ${{ secrets.YC_CLOUD }}

      - name: Configure folder
        uses: ./.github/actions/create-yc-folder
        with:
          name: ${{ needs.get-changes.outputs.yc_folder_name }}
          labels: "owner=${{ needs.get-changes.outputs.yc_owner }},expires_at=${{ needs.get-changes.outputs.yc_expires_at }}"


          
