name: Apply tf changes
on:
  push: {}

jobs:
  yc-config:
    runs-on: ubuntu-latest
    steps:
      - name: Install yc
        run: |
          apt update && apt install -y curl
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Configure yc
        shell: bash
        run: |
          PATH="~/yandex-cloud/bin:$PATH"
          yc config profile create default
          yc config set token {{ secrets.YC_TOKEN }}
          yc config set cloud-id {{ secrets.YC_CLOUD }}

      - shell: bash
        run: |
          PATH="~/yandex-cloud/bin:$PATH"
          yc config profile list