name: Apply tf changes
on:
  workflow_dispatch: {}
  push:
    branches:
    - '*'
    paths:
    - 'states/**'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/get-changes
          
  yc-config:
    runs-on: ubuntu-latest
    needs:
      - check-changes
    env:
      YC_FOLDER_NAME: ${{ needs.check-changes.outputs.yc_folder_name }}
      YC_OWNER: ${{ needs.check-changes.outputs.yc_owner }}
      YC_EXPIRES_AT: ${{ needs.check-changes.outputs.yc_expires_at }}
    steps:
      - name: Install yc
        run: |
          sudo apt update && sudo apt install -y curl
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Configure yc profile
        shell: bash
        run: |
          set -ex 
          PATH="~/yandex-cloud/bin:$PATH"
          yc config profile create terraform
          yc config set token ${{ secrets.YC_TOKEN }}
          yc config set cloud-id ${{ secrets.YC_CLOUD }}

      - name: Configure ${{ env.YC_FOLDER_NAME }} folder
        shell: bash
        run: |
          set -ex 
          PATH="~/yandex-cloud/bin:$PATH"
          
          yc resource-manager folder create ${{ env.YC_FOLDER_NAME }} || /bin/true
          yc resource-manager folder update --name ${{ env.YC_FOLDER_NAME }} --labels owner="${{ env.YC_OWNER }},expires=${{ env.YC_EXPIRES_AT }}"
          
