name: Apply tf changes
on:
  workflow_dispatch: {}
  push:
    branches:
    - '*'
    paths:
    - 'states/**'

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      yc_folder_name: ${{ steps.get-changes.outputs.yc_folder_name }}
      yc_owner: ${{ steps.get-changes.outputs.yc_owner }}
      yc_expires_at: ${{ steps.get-changes.outputs.yc_expires_at }}
    steps:
      - name: clean workspace
        uses: jstone28/runner-workspace-cleaner@v1.0.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/get-changes
        id: get-changes

  yc-config:
    runs-on: ubuntu-latest
    needs:
      - get-changes
    env:
      YC_FOLDER_NAME: ${{ needs.get-changes.outputs.yc_folder_name }}
      YC_OWNER: ${{ needs.get-changes.outputs.yc_owner }}
      YC_EXPIRES_AT: ${{ needs.get-changes.outputs.yc_expires_at }}
    steps:
      - name: Install yc
        run: |
          sudo apt update && sudo apt install -y curl
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Configure yc profile
        shell: bash
        run: |
          set -ex 
          PATH="~/yandex-cloud/bin:$PATH"
          yc config profile create terraform
          yc config set token ${{ secrets.YC_TOKEN }}
          yc config set cloud-id ${{ secrets.YC_CLOUD }}

      - name: Configure ${{ env.YC_FOLDER_NAME }} folder
        shell: bash
        run: |
          set -ex 
          PATH="~/yandex-cloud/bin:$PATH"
          
          yc resource-manager folder create ${{ env.YC_FOLDER_NAME }} || /bin/true
          yc resource-manager folder update --name ${{ env.YC_FOLDER_NAME }} --labels owner="${{ env.YC_OWNER }},expires=${{ env.YC_EXPIRES_AT }}"
          
